{{- if .Values.provider.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ck-ai.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ck-ai.labels" . | nindent 4 }}
type: Opaque
data:
  PROVIDER_TOKEN: {{ .Values.provider.token | b64enc | quote }}
{{- end }}
